const POSTS = [
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:1,
        title:"deneme2",
        file:"deneme2.md"
    },
    {
        id:2,
        title:"deneme3",
        file:"deneme3.md"
    },
    {
        id:3,
        title:"deneme4",
        file:"deneme4.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    },
    {
        id:0,
        title:"deneme1",
        file:"deneme.md"
    }
]

export default POSTS;